# Don't edit the `bin` list manually! It is updated by `cargo dev update`. This comment line will be stripped in `rustlings init`.
bin = [
  { name = "catalog_paths", path = "../exercises/01_catalog/catalog_paths.rs" },
  { name = "catalog_paths_sol", path = "../solutions/01_catalog/catalog_paths.rs" },
  { name = "catalog_defaults", path = "../exercises/01_catalog/catalog_defaults.rs" },
  { name = "catalog_defaults_sol", path = "../solutions/01_catalog/catalog_defaults.rs" },
  { name = "catalog_loading", path = "../exercises/01_catalog/catalog_loading.rs" },
  { name = "catalog_loading_sol", path = "../solutions/01_catalog/catalog_loading.rs" },
  { name = "solution_paths", path = "../exercises/01_catalog/solution_paths.rs" },
  { name = "solution_paths_sol", path = "../solutions/01_catalog/solution_paths.rs" },
  { name = "manifest_boundaries", path = "../exercises/01_catalog/manifest_boundaries.rs" },
  { name = "manifest_boundaries_sol", path = "../solutions/01_catalog/manifest_boundaries.rs" },
  { name = "manifest_targets", path = "../exercises/01_catalog/manifest_targets.rs" },
  { name = "manifest_targets_sol", path = "../solutions/01_catalog/manifest_targets.rs" },
  { name = "manifest_update", path = "../exercises/01_catalog/manifest_update.rs" },
  { name = "manifest_update_sol", path = "../solutions/01_catalog/manifest_update.rs" },
  { name = "cargo_metadata", path = "../exercises/02_checker/cargo_metadata.rs" },
  { name = "cargo_metadata_sol", path = "../solutions/02_checker/cargo_metadata.rs" },
  { name = "cargo_arguments", path = "../exercises/02_checker/cargo_arguments.rs" },
  { name = "cargo_arguments_sol", path = "../solutions/02_checker/cargo_arguments.rs" },
  { name = "process_status", path = "../exercises/02_checker/process_status.rs" },
  { name = "process_status_sol", path = "../solutions/02_checker/process_status.rs" },
  { name = "binary_location", path = "../exercises/02_checker/binary_location.rs" },
  { name = "binary_location_sol", path = "../solutions/02_checker/binary_location.rs" },
  { name = "command_tail", path = "../exercises/02_checker/command_tail.rs" },
  { name = "command_tail_sol", path = "../solutions/02_checker/command_tail.rs" },
  { name = "runtime_failure", path = "../exercises/02_checker/runtime_failure.rs" },
  { name = "runtime_failure_sol", path = "../solutions/02_checker/runtime_failure.rs" },
  { name = "checker_pipeline", path = "../exercises/02_checker/checker_pipeline.rs" },
  { name = "checker_pipeline_sol", path = "../solutions/02_checker/checker_pipeline.rs" },
  { name = "exercise_entry", path = "../exercises/02_checker/exercise_entry.rs" },
  { name = "exercise_entry_sol", path = "../solutions/02_checker/exercise_entry.rs" },
  { name = "solution_entry", path = "../exercises/02_checker/solution_entry.rs" },
  { name = "solution_entry_sol", path = "../solutions/02_checker/solution_entry.rs" },
  { name = "idempotent_directory", path = "../exercises/03_distribution/idempotent_directory.rs" },
  { name = "idempotent_directory_sol", path = "../solutions/03_distribution/idempotent_directory.rs" },
  { name = "chapter_readme", path = "../exercises/03_distribution/chapter_readme.rs" },
  { name = "chapter_readme_sol", path = "../solutions/03_distribution/chapter_readme.rs" },
  { name = "materialize_exercises", path = "../exercises/03_distribution/materialize_exercises.rs" },
  { name = "materialize_exercises_sol", path = "../solutions/03_distribution/materialize_exercises.rs" },
  { name = "restore_exercise", path = "../exercises/03_distribution/restore_exercise.rs" },
  { name = "restore_exercise_sol", path = "../solutions/03_distribution/restore_exercise.rs" },
  { name = "reveal_solution", path = "../exercises/03_distribution/reveal_solution.rs" },
  { name = "reveal_solution_sol", path = "../solutions/03_distribution/reveal_solution.rs" },
  { name = "initialize_workspace", path = "../exercises/03_distribution/initialize_workspace.rs" },
  { name = "initialize_workspace_sol", path = "../solutions/03_distribution/initialize_workspace.rs" },
  { name = "load_progress", path = "../exercises/04_progress/load_progress.rs" },
  { name = "load_progress_sol", path = "../solutions/04_progress/load_progress.rs" },
  { name = "pending_count", path = "../exercises/04_progress/pending_count.rs" },
  { name = "pending_count_sol", path = "../solutions/04_progress/pending_count.rs" },
  { name = "persist_progress", path = "../exercises/04_progress/persist_progress.rs" },
  { name = "persist_progress_sol", path = "../solutions/04_progress/persist_progress.rs" },
  { name = "select_index", path = "../exercises/04_progress/select_index.rs" },
  { name = "select_index_sol", path = "../solutions/04_progress/select_index.rs" },
  { name = "select_name", path = "../exercises/04_progress/select_name.rs" },
  { name = "select_name_sol", path = "../solutions/04_progress/select_name.rs" },
  { name = "completion_count", path = "../exercises/04_progress/completion_count.rs" },
  { name = "completion_count_sol", path = "../solutions/04_progress/completion_count.rs" },
  { name = "reopen_exercise", path = "../exercises/04_progress/reopen_exercise.rs" },
  { name = "reopen_exercise_sol", path = "../solutions/04_progress/reopen_exercise.rs" },
  { name = "reset_source", path = "../exercises/04_progress/reset_source.rs" },
  { name = "reset_source_sol", path = "../solutions/04_progress/reset_source.rs" },
  { name = "reset_current", path = "../exercises/04_progress/reset_current.rs" },
  { name = "reset_current_sol", path = "../solutions/04_progress/reset_current.rs" },
  { name = "reset_by_index", path = "../exercises/04_progress/reset_by_index.rs" },
  { name = "reset_by_index_sol", path = "../solutions/04_progress/reset_by_index.rs" },
  { name = "next_pending", path = "../exercises/04_progress/next_pending.rs" },
  { name = "next_pending_sol", path = "../solutions/04_progress/next_pending.rs" },
  { name = "solution_visibility", path = "../exercises/04_progress/solution_visibility.rs" },
  { name = "solution_visibility_sol", path = "../solutions/04_progress/solution_visibility.rs" },
  { name = "parallel_check_all", path = "../exercises/04_progress/parallel_check_all.rs" },
  { name = "parallel_check_all_sol", path = "../solutions/04_progress/parallel_check_all.rs" },
  { name = "save_check_all", path = "../exercises/04_progress/save_check_all.rs" },
  { name = "save_check_all_sol", path = "../solutions/04_progress/save_check_all.rs" },
  { name = "advance_progress", path = "../exercises/04_progress/advance_progress.rs" },
  { name = "advance_progress_sol", path = "../solutions/04_progress/advance_progress.rs" },
  { name = "finish_message", path = "../exercises/04_progress/finish_message.rs" },
  { name = "finish_message_sol", path = "../solutions/04_progress/finish_message.rs" },
  { name = "single_run_result", path = "../exercises/04_progress/single_run_result.rs" },
  { name = "single_run_result_sol", path = "../solutions/04_progress/single_run_result.rs" },
  { name = "terminal_budget", path = "../exercises/05_terminal/terminal_budget.rs" },
  { name = "terminal_budget_sol", path = "../solutions/05_terminal/terminal_budget.rs" },
  { name = "ascii_width", path = "../exercises/05_terminal/ascii_width.rs" },
  { name = "ascii_width_sol", path = "../solutions/05_terminal/ascii_width.rs" },
  { name = "unicode_width", path = "../exercises/05_terminal/unicode_width.rs" },
  { name = "unicode_width_sol", path = "../solutions/05_terminal/unicode_width.rs" },
  { name = "progress_counter", path = "../exercises/05_terminal/progress_counter.rs" },
  { name = "progress_counter_sol", path = "../solutions/05_terminal/progress_counter.rs" },
  { name = "progress_bar", path = "../exercises/05_terminal/progress_bar.rs" },
  { name = "progress_bar_sol", path = "../solutions/05_terminal/progress_bar.rs" },
  { name = "canonical_paths", path = "../exercises/05_terminal/canonical_paths.rs" },
  { name = "canonical_paths_sol", path = "../solutions/05_terminal/canonical_paths.rs" },
  { name = "file_link_frame", path = "../exercises/05_terminal/file_link_frame.rs" },
  { name = "file_link_frame_sol", path = "../solutions/05_terminal/file_link_frame.rs" },
  { name = "file_hyperlink", path = "../exercises/05_terminal/file_hyperlink.rs" },
  { name = "file_hyperlink_sol", path = "../solutions/05_terminal/file_hyperlink.rs" },
  { name = "ansi_buffer", path = "../exercises/05_terminal/ansi_buffer.rs" },
  { name = "ansi_buffer_sol", path = "../solutions/05_terminal/ansi_buffer.rs" },
  { name = "scroll_initial", path = "../exercises/06_navigation/scroll_initial.rs" },
  { name = "scroll_initial_sol", path = "../solutions/06_navigation/scroll_initial.rs" },
  { name = "scroll_window", path = "../exercises/06_navigation/scroll_window.rs" },
  { name = "scroll_window_sol", path = "../solutions/06_navigation/scroll_window.rs" },
  { name = "scroll_next", path = "../exercises/06_navigation/scroll_next.rs" },
  { name = "scroll_next_sol", path = "../solutions/06_navigation/scroll_next.rs" },
  { name = "scroll_previous", path = "../exercises/06_navigation/scroll_previous.rs" },
  { name = "scroll_previous_sol", path = "../solutions/06_navigation/scroll_previous.rs" },
  { name = "scroll_resize", path = "../exercises/06_navigation/scroll_resize.rs" },
  { name = "scroll_resize_sol", path = "../solutions/06_navigation/scroll_resize.rs" },
  { name = "scroll_padding", path = "../exercises/06_navigation/scroll_padding.rs" },
  { name = "scroll_padding_sol", path = "../solutions/06_navigation/scroll_padding.rs" },
  { name = "scroll_viewport", path = "../exercises/06_navigation/scroll_viewport.rs" },
  { name = "scroll_viewport_sol", path = "../solutions/06_navigation/scroll_viewport.rs" },
  { name = "list_model", path = "../exercises/06_navigation/list_model.rs" },
  { name = "list_model_sol", path = "../solutions/06_navigation/list_model.rs" },
  { name = "list_resize", path = "../exercises/06_navigation/list_resize.rs" },
  { name = "list_resize_sol", path = "../solutions/06_navigation/list_resize.rs" },
  { name = "list_rows", path = "../exercises/06_navigation/list_rows.rs" },
  { name = "list_rows_sol", path = "../solutions/06_navigation/list_rows.rs" },
  { name = "list_render", path = "../exercises/06_navigation/list_render.rs" },
  { name = "list_render_sol", path = "../solutions/06_navigation/list_render.rs" },
  { name = "list_filter", path = "../exercises/06_navigation/list_filter.rs" },
  { name = "list_filter_sol", path = "../solutions/06_navigation/list_filter.rs" },
  { name = "list_index_mapping", path = "../exercises/06_navigation/list_index_mapping.rs" },
  { name = "list_index_mapping_sol", path = "../solutions/06_navigation/list_index_mapping.rs" },
  { name = "list_reset", path = "../exercises/06_navigation/list_reset.rs" },
  { name = "list_reset_sol", path = "../solutions/06_navigation/list_reset.rs" },
  { name = "list_search", path = "../exercises/06_navigation/list_search.rs" },
  { name = "list_search_sol", path = "../solutions/06_navigation/list_search.rs" },
  { name = "list_open", path = "../exercises/06_navigation/list_open.rs" },
  { name = "list_open_sol", path = "../solutions/06_navigation/list_open.rs" },
  { name = "list_keys", path = "../exercises/06_navigation/list_keys.rs" },
  { name = "list_keys_sol", path = "../solutions/06_navigation/list_keys.rs" },
  { name = "list_lifecycle", path = "../exercises/06_navigation/list_lifecycle.rs" },
  { name = "list_lifecycle_sol", path = "../solutions/06_navigation/list_lifecycle.rs" },
  { name = "input_pause", path = "../exercises/07_watch/input_pause.rs" },
  { name = "input_pause_sol", path = "../solutions/07_watch/input_pause.rs" },
  { name = "debounce_updates", path = "../exercises/07_watch/debounce_updates.rs" },
  { name = "debounce_updates_sol", path = "../solutions/07_watch/debounce_updates.rs" },
  { name = "file_notifications", path = "../exercises/07_watch/file_notifications.rs" },
  { name = "file_notifications_sol", path = "../solutions/07_watch/file_notifications.rs" },
  { name = "terminal_events", path = "../exercises/07_watch/terminal_events.rs" },
  { name = "terminal_events_sol", path = "../solutions/07_watch/terminal_events.rs" },
  { name = "watch_model", path = "../exercises/07_watch/watch_model.rs" },
  { name = "watch_model_sol", path = "../solutions/07_watch/watch_model.rs" },
  { name = "watch_run", path = "../exercises/07_watch/watch_run.rs" },
  { name = "watch_run_sol", path = "../solutions/07_watch/watch_run.rs" },
  { name = "watch_reset", path = "../exercises/07_watch/watch_reset.rs" },
  { name = "watch_reset_sol", path = "../solutions/07_watch/watch_reset.rs" },
  { name = "watch_change", path = "../exercises/07_watch/watch_change.rs" },
  { name = "watch_change_sol", path = "../solutions/07_watch/watch_change.rs" },
  { name = "watch_completion", path = "../exercises/07_watch/watch_completion.rs" },
  { name = "watch_completion_sol", path = "../solutions/07_watch/watch_completion.rs" },
  { name = "watch_advance", path = "../exercises/07_watch/watch_advance.rs" },
  { name = "watch_advance_sol", path = "../solutions/07_watch/watch_advance.rs" },
  { name = "watch_prompt", path = "../exercises/07_watch/watch_prompt.rs" },
  { name = "watch_prompt_sol", path = "../solutions/07_watch/watch_prompt.rs" },
  { name = "watch_render", path = "../exercises/07_watch/watch_render.rs" },
  { name = "watch_render_sol", path = "../solutions/07_watch/watch_render.rs" },
  { name = "watch_hint", path = "../exercises/07_watch/watch_hint.rs" },
  { name = "watch_hint_sol", path = "../solutions/07_watch/watch_hint.rs" },
  { name = "watch_check_all", path = "../exercises/07_watch/watch_check_all.rs" },
  { name = "watch_check_all_sol", path = "../solutions/07_watch/watch_check_all.rs" },
  { name = "watch_resize", path = "../exercises/07_watch/watch_resize.rs" },
  { name = "watch_resize_sol", path = "../solutions/07_watch/watch_resize.rs" },
  { name = "watch_dispatch", path = "../exercises/07_watch/watch_dispatch.rs" },
  { name = "watch_dispatch_sol", path = "../solutions/07_watch/watch_dispatch.rs" },
  { name = "watch_list_transition", path = "../exercises/07_watch/watch_list_transition.rs" },
  { name = "watch_list_transition_sol", path = "../solutions/07_watch/watch_list_transition.rs" },
  { name = "watch_start", path = "../exercises/07_watch/watch_start.rs" },
  { name = "watch_start_sol", path = "../solutions/07_watch/watch_start.rs" },
  { name = "editor_process", path = "../exercises/08_editors/editor_process.rs" },
  { name = "editor_process_sol", path = "../solutions/08_editors/editor_process.rs" },
  { name = "editor_discovery", path = "../exercises/08_editors/editor_discovery.rs" },
  { name = "editor_discovery_sol", path = "../solutions/08_editors/editor_discovery.rs" },
  { name = "editor_selection", path = "../exercises/08_editors/editor_selection.rs" },
  { name = "editor_selection_sol", path = "../solutions/08_editors/editor_selection.rs" },
  { name = "editor_launch", path = "../exercises/08_editors/editor_launch.rs" },
  { name = "editor_launch_sol", path = "../solutions/08_editors/editor_launch.rs" },
  { name = "editor_close", path = "../exercises/08_editors/editor_close.rs" },
  { name = "editor_close_sol", path = "../solutions/08_editors/editor_close.rs" },
  { name = "editor_join", path = "../exercises/08_editors/editor_join.rs" },
  { name = "editor_join_sol", path = "../solutions/08_editors/editor_join.rs" },
  { name = "pane_identifier", path = "../exercises/08_editors/pane_identifier.rs" },
  { name = "pane_identifier_sol", path = "../solutions/08_editors/pane_identifier.rs" },
  { name = "pane_status", path = "../exercises/08_editors/pane_status.rs" },
  { name = "pane_status_sol", path = "../solutions/08_editors/pane_status.rs" },
  { name = "pane_close", path = "../exercises/08_editors/pane_close.rs" },
  { name = "pane_close_sol", path = "../solutions/08_editors/pane_close.rs" },
  { name = "app_editor_start", path = "../exercises/08_editors/app_editor_start.rs" },
  { name = "app_editor_start_sol", path = "../solutions/08_editors/app_editor_start.rs" },
  { name = "app_editor_join", path = "../exercises/08_editors/app_editor_join.rs" },
  { name = "app_editor_join_sol", path = "../solutions/08_editors/app_editor_join.rs" },
  { name = "app_editor_close", path = "../exercises/08_editors/app_editor_close.rs" },
  { name = "app_editor_close_sol", path = "../solutions/08_editors/app_editor_close.rs" },
  { name = "author_names", path = "../exercises/09_authoring/author_names.rs" },
  { name = "author_names_sol", path = "../solutions/09_authoring/author_names.rs" },
  { name = "author_manifest", path = "../exercises/09_authoring/author_manifest.rs" },
  { name = "author_manifest_sol", path = "../solutions/09_authoring/author_manifest.rs" },
  { name = "author_catalog", path = "../exercises/09_authoring/author_catalog.rs" },
  { name = "author_catalog_sol", path = "../solutions/09_authoring/author_catalog.rs" },
  { name = "author_file_inventory", path = "../exercises/09_authoring/author_file_inventory.rs" },
  { name = "author_file_inventory_sol", path = "../solutions/09_authoring/author_file_inventory.rs" },
  { name = "author_unsolved", path = "../exercises/09_authoring/author_unsolved.rs" },
  { name = "author_unsolved_sol", path = "../solutions/09_authoring/author_unsolved.rs" },
  { name = "author_format", path = "../exercises/09_authoring/author_format.rs" },
  { name = "author_format_sol", path = "../solutions/09_authoring/author_format.rs" },
  { name = "author_solutions", path = "../exercises/09_authoring/author_solutions.rs" },
  { name = "author_solutions_sol", path = "../solutions/09_authoring/author_solutions.rs" },
  { name = "author_gate", path = "../exercises/09_authoring/author_gate.rs" },
  { name = "author_gate_sol", path = "../solutions/09_authoring/author_gate.rs" },
  { name = "author_directories", path = "../exercises/09_authoring/author_directories.rs" },
  { name = "author_directories_sol", path = "../solutions/09_authoring/author_directories.rs" },
  { name = "author_files", path = "../exercises/09_authoring/author_files.rs" },
  { name = "author_files_sol", path = "../solutions/09_authoring/author_files.rs" },
  { name = "author_new_course", path = "../exercises/09_authoring/author_new_course.rs" },
  { name = "author_new_course_sol", path = "../solutions/09_authoring/author_new_course.rs" },
  { name = "author_update_manifest", path = "../exercises/09_authoring/author_update_manifest.rs" },
  { name = "author_update_manifest_sol", path = "../solutions/09_authoring/author_update_manifest.rs" },
  { name = "author_update", path = "../exercises/09_authoring/author_update.rs" },
  { name = "author_update_sol", path = "../solutions/09_authoring/author_update.rs" },
  { name = "author_dispatch", path = "../exercises/09_authoring/author_dispatch.rs" },
  { name = "author_dispatch_sol", path = "../solutions/09_authoring/author_dispatch.rs" },
  { name = "embedded_macro", path = "../exercises/10_launch/embedded_macro.rs" },
  { name = "embedded_macro_sol", path = "../solutions/10_launch/embedded_macro.rs" },
  { name = "launch_dispatch", path = "../exercises/10_launch/launch_dispatch.rs" },
  { name = "launch_dispatch_sol", path = "../solutions/10_launch/launch_dispatch.rs" },
]

[package]
name = "exercises"
edition = "2024"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lints.rust]
# You shouldn't write unsafe code in Rustlings!
unsafe_code = "forbid"
# You don't need unstable features in Rustlings and shouldn't rely on them while learning Rust.
unstable_features = "forbid"
# Dead code warnings can't be avoided in some exercises and might distract while learning.
dead_code = "allow"

[lints.clippy]
# You forgot a `todo!()`!
todo = "forbid"
# This can only happen by mistake in Rustlings.
empty_loop = "forbid"
# No infinite loops are needed in Rustlings.
infinite_loop = "deny"
# You shouldn't leak memory while still learning Rust!
mem_forget = "deny"
# Currently, there are no disallowed methods. This line avoids problems when developing Rustlings.
disallowed_methods = "allow"
