base_url = "https://quasarray.github.io/rustlings"
title = "Rebuild the Checker"
description = "Restore the real Rustlings checker through 112 advanced missions."

compile_sass = false
build_search_index = false

[markdown]
insert_anchor_links = "heading"

[markdown.highlighting]
theme = "dracula"

[extra]
logo_path = "images/happy_ferris.svg"

[[extra.menu_items]]
name = "Rustlings"
url = "@/_index.md"
[[extra.menu_items]]
name = "Setup"
url = "@/setup/index.md"
[[extra.menu_items]]
name = "Usage"
url = "@/usage/index.md"
[[extra.menu_items]]
name = "Community Exercises"
url = "@/community-exercises/index.md"
[[extra.menu_items]]
name = "Q&A"
url = "https://github.com/QuasarRay/rustlings/discussions/categories/q-a?discussions_q="

[[extra.footer_items]]
name = "Repository"
url = "https://github.com/QuasarRay/rustlings"
[[extra.footer_items]]
name = "Changelog"
url = "https://github.com/QuasarRay/rustlings/blob/main/CHANGELOG.md"
[[extra.footer_items]]
name = "MIT License"
url = "https://github.com/QuasarRay/rustlings/blob/main/LICENSE"
